baseURL = 'https://suchismita-deb.github.io/'
languageCode = 'en-us'
title = 'Technical Blog'
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'Suchismita-Deb'                 # github.com/Suchismita-Deb
  linkedin = 'debsuchismita'             # linkedin.com/in/YOUR_LINKEDIN_ID
  

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'SUCHISMITA DEB'
  bio = 'Software Developer'